config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :movies, only: [:index] do
    resources :screens, only: [:index]
    resources :reports, only: [:index]
  end

  resources :movie_screens, only:[] do
    resources :reservations, only: [:index] do
      member do
        get :book
        get :order
      end
      collection do
        post 'cart_action'
        post 'clear_cart'
      end
    end
  end

  resources :users, only: [:index] do
    resources :reports, only: [] do
      collection do 
        get :bookings
      end
    end
  end

  authenticated :user, ->(u) { u.customer? } do
    root to: 'movies#index', as: "dashboard"
  end

  devise_scope :user do
    root "devise/sessions#new"
  end
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

# This controller will handle movie related requests
class MoviesController < ApplicationController
  before_action :authenticate_user!

  def index
    # This will fetch all movies with show for future date
    @movies = if current_user.admin?
                Movie.distinct('movies.id').order(:release_date)
              else
                Movie.joins(:movie_screens).where('start_time > ?', Time.now).distinct('movies.id').order(:release_date)
              end
    # Fecth upcoming movies
  end
end

app/helpers/movies_helper.rb
# frozen_string_literal: true

# Movies helper
module MoviesHelper
end

app/views/movies/index.html.haml
.row
  .col-12
    - @movies.each_slice(3) do |movies_array|
      .card-deck.justify-content-center.mt-5
        - movies_array.each do |movie|
          .card.col-3
            - path = current_user.admin? ? movie_reports_path(movie.id) : movie_screens_path(movie.id)
            = link_to path, { class: 'card-link'} do
              = image_tag movie.image_url, { class: "card-img-top"}
              .card-body
                %h5.card-title #{movie.name} (#{movie.language})
                %p.card-text= movie.description
                %p.card-text
                  %small.text-muted Released on #{movie.release_date} | Duration: #{movie.duration}