config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :movies, only: [:index] do
    resources :screens, only: [:index]
    resources :reports, only: [:index]
  end

  resources :movie_screens, only:[] do
    resources :reservations, only: [:index] do
      member do
        get :book
        get :order
      end
      collection do
        post 'cart_action'
        post 'clear_cart'
      end
    end
  end

  resources :users, only: [:index] do
    resources :reports, only: [] do
      collection do 
        get :bookings
      end
    end
  end

  authenticated :user, ->(u) { u.customer? } do
    root to: 'movies#index', as: "dashboard"
  end

  devise_scope :user do
    root "devise/sessions#new"
  end
end

app/models/reservation.rb
# frozen_string_literal: true

# This class will perform operations related to reservation
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :movie_screen
  has_many :reservation_seats, dependent: :destroy

  before_save :calculate_price

  private

  def calculate_price
    self.price = reservation_seats.pluck(:price).sum
  end
end

app/controllers/reservations_controller.rb
# frozen_string_literal: true

# Reservation controller
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_movie_screen
  before_action :load_seat, only: [:cart_action]
  before_action :active_reservation_and_seats, only: %i[cart_action index]
  before_action :load_reservation, only: %i[book order]

  def index
    reservation_data
  end

  def cart_action
    if params[:user_action].eql?('add')
      @seats.create(seat_id: @seat.id, price: @seat.price)
    else
      @seats.find_by(seat_id: @seat.id)&.destroy
    end
    @active_reservation.save
    reservation_data
    render action: 'cart_action', layout: false
  end

  def book
    @reservation.update_attributes(paid: true)
    flash[:success] = I18n.t('reservation.book')
    redirect_to order_movie_screen_reservation_path(@reservation.movie_screen.movie_id, @reservation.id)
  end

  def clear_cart
    current_user.reservations.where(paid: false).destroy_all
    reservation_data
    render action: 'cart_action', layout: false
  end

  def order; end

  private

  def active_reservation_and_seats
    params = { active: true, paid: false, movie_screen_id: @movie_screen.id }
    @active_reservation = current_user.reservations.find_or_create_by(params)
    @seats = @active_reservation.reservation_seats
  end

  def reservation_data
    @reserved_seats = @movie_screen.reserved_seats
    @selected_seats = @movie_screen.selected_seats(current_user.id).pluck('seats.number')
    @columns = Screen::COLUMNS
    @rows = Screen::ROWS
    @price_ranges = Screen::SEATS
    @total = @active_reservation&.price
  end

  def load_movie_screen
    @movie_screen = MovieScreen.find_by(id: params[:movie_screen_id])
  end

  def load_seat
    @seat = @movie_screen.seats.find_by(number: params[:current][:index])
  end

  def load_reservation
    @reservation = Reservation.find_by(id: params[:id])
  end
end

app/helpers/reservations_helper.rb
# frozen_string_literal: true

# Reservation helper
module ReservationsHelper
end

app/views/reservations/_seat_chart.html.haml
.row
  #map-container
  #legend-container
    %h1 Price Range 
    - @price_ranges.each do |pr|
      = "#{pr[:rows].join(',')}: #{pr[:price]} RS"
      %br
  #shoppingCart-container
    %h3 Total: #{@total}
.row
  .col-5
  - if @active_reservation.reservation_seats.present?
    = link_to "Book Now", book_movie_screen_reservation_path(@movie_screen.id, @active_reservation.id), :data => {:confirm => 'Are you sure?'}, class: 'btn btn-primary'
:javascript
  function searchChartCallback() {
              var options = {
             // Reserved and disabled seats are indexed
             // from left to right by starting from 0.
             // Given the seatmap as a 2D array and an index [R, C]
             // the following values can obtained as follow:
             // I = columns * R + C
             map: {
                 id: 'map-container',
                 rows: #{@rows},
                 columns: #{@columns},
                 // e.g. Reserved Seat [Row: 1, Col: 2] = 7 * 1 + 2 = 9
                 reserved: {
                     seats: #{@reserved_seats},
                 },
                 disabled: {
                     seats: [],
                     rows: [],
                     columns: []
                 }
             },
             types: [
                 { type: "regular", backgroundColor: "#006c80", price: 200, selected: #{@selected_seats} },
             ],
             cart: {
                 id: 'shoppingCart-container',
                 width: 280,
                 height: 250,
                 currency: 'Rs',
             },
             assets: {
                 path: "/seatchart/assets",
             }
         };
         var sc = new Seatchart(options);
         sc.onChange = function(e) {
         $.ajax({
           type: "POST",
           url: 'reservations/cart_action',
           data: {"user_action": e.action, "current": e.current },
           dataType: 'html',
           complete: function(data){ $('#seat_chart').html(data.responseText) ; searchChartCallback() },
        });
          }

         sc.onClear = function(e) {
         $.ajax({
           type: "POST",
           url: 'reservations/clear_cart',
           dataType: 'html',
           complete: function(data){ $('#seat_chart').html(data.responseText) ; searchChartCallback() },
        });
        }
      }

%script{:onload => "searchChartCallback()", :src => "/seatchart/seatchart.js"}

app/views/reservations/cart_action.html.haml
%link{:href => "/seatchart/seatchart.css", :rel => "stylesheet"}/
#seat_chart
  = render 'seat_chart', :locals => { reserved_seats: @reserved_seats, columns: @columns, rows: @rows }

app/views/reservations/index.html.haml
%link{:href => "/seatchart/seatchart.css", :rel => "stylesheet"}/
#seat_chart
  = render 'seat_chart', :locals => { reserved_seats: @reserved_seats, columns: @columns, rows: @rows }

app/views/reservations/order.html.haml
.row
  .col-4
  .col-4
    .card.border-primary.mb-3
      .card-header Congratulations, Your booking is successful
      .card-body.text-primary
        %h5.card-title="Movie Name #{@reservation.movie_screen.movie.name}"
        %p.card-text= "Date: #{@reservation.movie_screen.start_time}"
  .col-4