config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :movies, only: [:index] do
    resources :screens, only: [:index]
    resources :reports, only: [:index]
  end

  resources :movie_screens, only:[] do
    resources :reservations, only: [:index] do
      member do
        get :book
        get :order
      end
      collection do
        post 'cart_action'
        post 'clear_cart'
      end
    end
  end

  resources :users, only: [:index] do
    resources :reports, only: [] do
      collection do 
        get :bookings
      end
    end
  end

  authenticated :user, ->(u) { u.customer? } do
    root to: 'movies#index', as: "dashboard"
  end

  devise_scope :user do
    root "devise/sessions#new"
  end
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-sm.bg-light.justify-content-between
  %a.navbar-brand{:href => "#"} Movie Booking Application
  / Links
  %ul.navbar-nav
    - if current_user.present?
      %li.nav-item
        = link_to "Log out", destroy_user_session_path, method: :delete
      - if current_user.admin?
        %li.nav-item
          = link_to "| Movie Reports", movies_path
        %li.nav-item
          = link_to "| User Reports", users_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MovieBooking
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css'
    = javascript_include_tag 'https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js'
    = javascript_include_tag 'https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js'
  %body
    = render 'layouts/header'
    - if current_user
      .row.mt-5
        .col-md-2
        .col-md-9
          - unless flash.blank?
            = render 'shared/flash'
      = yield
    - else
      .row
        .col-md-3
        .col-md-6
          - unless flash.blank?
            = render 'shared/flash'
          = yield